server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          dongho-client-oidc:
            provider: spring
            client-id: dongho-client-authorization-code
            client-secret: 1234
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: dongho-client-client-oidc
          dongho-client-authorization-code:
            provider: spring
            client-id: dongho-client-authorization-code
            client-secret: 1234
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: articles.read
            client-name: dongho-client-authorization-code
          dongho-client-client-credential:
            provider: spring
            client-id: dongho-client-client-credential
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/client_credential_authorized"
            scope: articles.read
            client-name: dongho-client-client-credential
        provider:
          spring:
            issuer-uri: http://auth-server:8081
