server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          client-oidc:
            provider: spring
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: client-name
          dongho-client-authorization-code:
            provider: spring
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: test-scope
            client-name: client-name
          dongho-client-client-credential:
            provider: spring
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: client_credentials
            scope: test-scope
            client-name: client-name
            clientAuthenticationMethod: POST
        provider:
          spring:
            issuer-uri: http://auth-server:8081
